name: Deploy cache

on:
  push:
    branches:
      - master

jobs:
  build-cache:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Run Python script
      run: |
        python generate-cache.py

    - name: Commit files to gh-pages branch
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'

        # Create and checkout the gh-pages branch
        git checkout origin/gh-pages

        # Pull changes from the gh-pages branch
        git pull

        # Merge master into gh-pages
        git pull origin master

        # Add all generated files (if your script generates files to be committed)
        git add cache/

        # Commit the changes
        git commit -m "Deploy cache to gh-pages"

        # Push changes to the gh-pages branch
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
